In [4]:
import numpy as np

In [5]:
a = np.array(np.arange(40).reshape(5, 8))

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

## 如何选取第1、3、4行，第3、5列的数据？
参考资料  
1. [Selecting specific rows and columns from NumPy array
](https://stackoverflow.com/questions/22927181/selecting-specific-rows-and-columns-from-numpy-array)
2. [Indexing](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html)

### 1. 使用两次索引

In [9]:
a[[1,3,4], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [71]:
a[[1,3,4], :][:, [3,5]]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [75]:
a[1,3,4]

IndexError: too many indices for array

In [76]:
a[[1,3,4]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [77]:
a[[1,3,4]][:, [3,5]] # a[维度1列表, 维度2列表]，如果省略维度2列表，则默认为 :

array([[11, 13],
       [27, 29],
       [35, 37]])

### 2. 使用np.ix_，标准方法，最好理解

In [13]:
a.ix_([[1,3,4],[3,5]])

AttributeError: 'numpy.ndarray' object has no attribute 'ix_'

In [15]:
a[np.ix_([1,3,4],[3,5])]

array([[11, 13],
       [27, 29],
       [35, 37]])

### 3. 使用布尔索引数组，改方法没有成功

In [22]:
b = np.array([False,True,False,True,True])

In [19]:
a[b]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [24]:
b2 = np.array([False,False,False,True,False,True,False,False], axis=0)

TypeError: 'axis' is an invalid keyword argument for this function

In [23]:
a[b][b2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 8

### 4. 使用索引数组

In [25]:
# a[[维度1的索引], [维度2的索引]] => 定位1个元素
a[[1], [3]]

array([11])

In [29]:
a[[1,1], [3,5]] # 定位2个元素

array([11, 13])

In [30]:
a[[1,1,1], [3,5,6]] # 定位3个元素

array([11, 13, 14])

In [31]:
a[[1,1,1], [3,5]] # 错误写法，从上面的写法可以发现规律，两个维度的索引数组长度必须一致

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [32]:
a[[1,1,1],[3]] # 而只写1个3却又是对的，因为numpy默认扩展为[3,3,3]

array([11, 11, 11])

In [27]:
a[[[1,1], [3,5]],
  [[3,3], [3,5]],
  [[4,4], [3,5]]] # 错误写法，分行应该在[1,1那里]

IndexError: too many indices for array

In [28]:
# a[[[1,1], [3,3], [4,4]]]
a[[[1,1], [3,3], [4,4]], [[3,5], [3,5], [3,5]]]

array([[11, 13],
       [27, 29],
       [35, 37]])

利用同一个数组[]内的广播broadcasting性质，也就是[1]会根据需要自动扩展为[1,1,...]，所以可以把单个[]内的相同元素都只写1个，嵌套成立！

In [33]:
a[[[1],[3],[4]], [3,5]]

array([[11, 13],
       [27, 29],
       [35, 37]])

### 5. np.ix_方法的变形，理解麻烦

之前不使用np.ix_打包的时候是错的：

In [34]:
a[[1,3,4], [3,5]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [35]:
a[np.array([1,3,4]), np.array([3,5])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

后来使用了np.ix_打包

In [37]:
# a[np.ix_([1,3,4],[3,5]) # 少了1个方括号
a[np.ix_([1,3,4],[3,5])]

array([[11, 13],
       [27, 29],
       [35, 37]])

下面的方法其实和第4个方法最后一个形式一致，利用了broadcasting的性质

In [38]:
row_idx = [1,3,4] # 错误，必须是np.array格式
col_idx = [3,5]
a[row_idx[:, None], col_idx]

TypeError: list indices must be integers or slices, not tuple

In [101]:
row_idx = np.array([1,3,4]) # np.array可以用
col_idx = np.array([3,5]) # np.array可以用
a[row_idx[:, None], col_idx]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [103]:
a[np.array([1,3,4])[:, None], [3,5]]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [44]:
row_idx

array([1, 3, 4])

In [46]:
row_idx[:]

array([1, 3, 4])

In [53]:
row_idx.ndim

1

In [48]:
row_idx.shape

(3,)

In [55]:
row_idx[:, None] # 1维向量变成2维数组了

array([[1],
       [3],
       [4]])

In [54]:
row_idx[:, None].ndim

2

In [50]:
row_idx[:, None].shape

(3, 1)

In [57]:
row_idx[None, :]

array([[1, 3, 4]])

In [59]:
row_idx[None, :].ndim

2

In [90]:
row_idx[None, :].shape

(1, 3)

In [91]:
a[row_idx[None, :], col_idx]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (1,3) (2,) 

In [93]:
a[row_idx, col_idx[None, :]] # 为什么没有用呢？？？

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (1,2) 

In [94]:
col_idx[None, :]

array([[3, 5]])

In [95]:
row_idx

array([1, 3, 4])

In [104]:
a[row_idx, 3:(5+1):2]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [106]:
a[[1,3,4], 3:(5+1):2]

array([[11, 13],
       [27, 29],
       [35, 37]])

### 6. 方法4的补充，组合索引index array和切片slices

In [78]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [79]:
a[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [80]:
a[::3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [81]:
::2

SyntaxError: invalid syntax (<ipython-input-81-b7fa2718cbbb>, line 1)

In [82]:
np.array([::2])

SyntaxError: invalid syntax (<ipython-input-82-a16dffce94dc>, line 1)

**加入列是从0开始等差数列，则有如下奇怪的形式成立，原来是组合索引数组和切片的方法**

In [83]:
a[[1,3,4], [0, 3, 6]]

array([ 8, 27, 38])

In [85]:
a[[1,3,4], ::3] # 和上一个cell比较

array([[ 8, 11, 14],
       [24, 27, 30],
       [32, 35, 38]])

In [89]:
a[[1,3,4], 3:(5+1):2]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [98]:
a[[False,True,False,True,True], 3:(5+1):2] # 利用索引数组和布尔向量索引的等价性

array([[11, 13],
       [27, 29],
       [35, 37]])

In [99]:
a[[1,3,4],slice(3,5)] # 这种写法最简单了

array([[11, 12],
       [27, 28],
       [35, 36]])

In [107]:
a[slice(1,3,4),slice(3,5)] 

array([[11, 12]])

In [109]:
a.ix_([[1,3,4],[3,5]])

AttributeError: 'numpy.ndarray' object has no attribute 'ix_'

```python
a[[1,3,4]][:, [3,5]] 等价于 a[[1, 3, 4], :][:, [3, 5]]  
a.ix_([[1,3,4],[3,5]]) 错误改成 a[np.ix_([1,3,4],[3,5])]  
a[[[1,1], [3,3], [4,4]], [[3,5], [3,5], [3,5]]]  
a[[[1],[3],[4]], [3,5]] 等价于 a[[[1,1], [3,3], [4,4]], [[3,5], [3,5], [3,5]]]
a[np.array([1,3,4])[:, None], [3,5]] 等价于 a[[[1],[3],[4]], [3,5]] 
a[[1,3,4], 3:(5+1):2]
a[[1,3,4], slice(3,5)]  等价于 a[[1,3,4], 3:(5+1):2]
a[[False,True,False,True,True], 3:(5+1):2] 等价于 a[[1,3,4], 3:(5+1):2]
```