## [Indexing](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html)
See also:  
[Indexing routines](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.indexing.html#routines-indexing)
数组（array）索引指的是利用方括号（[]）来索引数组数值。索引有很多选项，给与了numpy index强大的能力，但是也带来了复杂和混淆。这节主要是一个概述，讲解和index相关的不同选项和问题。除了单个元素的索引，这些选项的详细应用可以在相关的小节里面了解

### 赋值和引用  
### Assignment vs referencing
下面大部分的例子都是演示了引用数组数据时的索引使用。不会翻译了。

### 单个元素索引
### Single element indexing
1维数组的单个元素的索引正如所期望的一样。同样对其他标准Python序列也适用。索引从0开始，同时支持从末尾开始的负数索引。

In [3]:
import numpy as np

In [4]:
x = np.arange(10) # 产生一个等差序列

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[2]

2

In [7]:
x[-1]

9

In [8]:
x[-2]

8

和列表以及元组不同，numpy的数组支持多维数组的多维索引。也就是说它不需要像索引普通数组单个元素那样，把每个维度的的索引写到单独的方括号中去。

In [9]:
x.shape

(10,)

In [10]:
x.shape = (2, 5) # 现在x就变成了一个2维向量

In [11]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
x[1, 3]

8

In [14]:
x[1, -1]

9

注意如果一个人索引一个多维数组，但是索引数小于维度，则得到一个低纬度的数组。

In [15]:
x[0]

array([0, 1, 2, 3, 4])

In [16]:
x[0, :]

array([0, 1, 2, 3, 4])

也就是说，每个索引选择了数组相应的余下的维度。上例中，选择0意味着剩下的长度为5的维度没有被定义，所以返回的就是那个维度和大小。  
需要注意的是返回的数组不是原来数组的拷贝，而是原来数值的在内存中的引用。  
在这种情况下，一个1维的数组在位置0被返回了。  
所以对返回的数组再次使用单个索引，则返回了一个元素。  

In [17]:
x[0][2]

2

所以注意到'x[0, 2] = x[0][2]'的第2种写法是低效率的，因为在第1次索引后产生了临时数组，然后再在临时数组上作用第2个索引。  
这里关于内存排布的不会翻译了，搜到一些[谷歌资料这里](https://www.google.com/search?q=NumPy+uses+C-order+indexing&hl=en-US&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjwuqz1trPYAhVP72MKHQ7YAp8Q_AUIDSgE&biw=1442&bih=796#imgrc=qNa9l3zM7huGlM:)。

### 其他索引选项
### Other indexing options
为了分割和stride一个数组得到相同维度的数组，但是和原来的数组大小不一致。  
分割和striding的工作方式和列表与元组的工作方式是一样的，除了他们能被应用于多维。

In [18]:
x = np.arange(10) # 产生一个1维的等差数列

In [19]:
x[2:5]

array([2, 3, 4])

In [20]:
x[:-7]

array([0, 1, 2])

In [21]:
x[1:7:2] # 最后一个2是间隔

array([1, 3, 5])

In [22]:
y = np.arange(35).reshape(5, 7)

In [23]:
y[1:5:2, ::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [24]:
1:5:2

SyntaxError: invalid syntax (<ipython-input-24-aa78870a13c7>, line 1)

In [25]:
1:5

SyntaxError: illegal target for annotation (<ipython-input-25-9f2408835f22>, line 1)

注意数组的切片没有拷贝内部数组数据而仅仅是创造了原始数据的新的视角。  
可以索引数组使用其他的数组，从而把数组里的一个列表的数据导入到新的数组里面。有两种不同的方法来实现这个。  
一个是使用一个或者多个索引值得数组。  
另外一个就是使用布尔数组的合适形状来索引被选中的值。
索引数组是一个非常强大的工具避免了使用循环遍历每一个单独的数组元素，从而提高了性能。  
不会翻译了。  
可能使用特殊的特征来有效地增加。。。

### 索引数组
### Index arrays 
Numpy数组可能通过其他数组来索引，或者任何其他的序列，这个序列可以被转换为数组，比如列表，但是元组tuples不可以；可以看本文档的最后一部分。索引数组从简单，直接的到复杂的，难以理解的格式都有。对于所有这些所有索引数组格式，返回的是一个拷贝而不是引用。  
索引数组必须是整型。索引数组的每个值显示了数组的那个索引的值。比如：  

In [26]:
x = np.arange(10, 1, -1) # 产生等差数列

In [27]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [28]:
x[[3, 3, 1, 8]]

array([7, 7, 9, 2])

In [30]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [31]:
x[(3, 3, 1, 8)] # tuples not work

IndexError: too many indices for array

索引数组由多个值构成，相应地构成了一个长度为4的数组，其中每个索引用对应的原数组的索引对应的值代替。  
负数是允许的，比如单个索引或者切片如下：

In [32]:
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

超出索引则是不对的

In [33]:
x[np.array([3, 3, 20, 8])]

IndexError: index 20 is out of bounds for axis 0 with size 9

通常而言，如果索引数组的多个数组的形状一致，也是可以的。比如，我们能够使用多维数组索引如下：

In [60]:
x[np.array([[1, 1, 1], [2, 3, 3]])]

array([[9, 9, 9],
       [8, 7, 7]])

In [36]:
x[np.ix_([1, 1], [2, 3])]

IndexError: too many indices for array

In [38]:
a = np.array(np.arange(40).reshape(5, 8))
 
row = [1, 3, 4]
col = [3, 5]
a[np.ix_(row, col)]
a[np.ix_([1, 3, 4], [3, 5])]

array([[11, 13],
       [27, 29],
       [35, 37]])

In [58]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [55]:
x[np.array([1, 3, 4], [3, 5])]

TypeError: data type not understood

In [57]:
x[np.array([[1, 3, 4], [3, 5, 3]])]

TypeError: data type not understood

In [52]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [53]:
a[np.array([1, 3, 4], [3, 5])]

TypeError: data type not understood

### 索引多维数组
### Indexing Multi-dimensional arrays
多维数组使得问题变得困难了，尤其是索引多维数组。

In [44]:
y[np.array([0,2,4]), np.array([0,1,2])] # 取的是一组点的索引对，而不是对数组的整体提取

array([ 0, 15, 30])

In [45]:
y[np.array([0,2,4]), np.array([0,1,2])][0] = 100 # 显然得到的是数组的拷贝，因为100没有改变原来数组的元素内容

In [46]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [47]:
y[np.ix_([0, 2, 4], [0, 1, 2])] # 这种提取方式更符合要求

array([[ 0,  1,  2],
       [14, 15, 16],
       [28, 29, 30]])

In [48]:
y[np.array([0, 2, 4], [0, 1, 2])] # 这种单个的np.array只能用来对1维向量的元素进行选取重排为特定的矩阵

TypeError: data type not understood

In [61]:
y[np.array([[0, 2, 4], [0, 1, 2]])] # 会把矩阵当成1维向量处理，只不过元素变成了向量

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [14, 15, 16, 17, 18, 19, 20],
        [28, 29, 30, 31, 32, 33, 34]],

       [[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]]])

In [42]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [43]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

在这种情况下，如果索引数组有一个匹配的形状，并且每个维度上都有索引数组，结果数组就具有和索引数组相同的维度。  
如果索引数组没有相同的形状，则会广播他们到相同的形状，也就是默认都用这个值替代。如果无法广播到相同的形状，比如有两个值，则报异常：

In [62]:
y[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [64]:
y[np.array([0,2,4]), np.array([0])]

array([ 0, 14, 28])

In [65]:
y[np.array([0,2,4]), 0] # 允许使用单个数值来广播

array([ 0, 14, 28])

In [66]:
y[np.array([0,2,4])] # 对行向量进行索引

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [67]:
y[[0,2,4], [1,3,4]]

array([ 1, 17, 32])

In [68]:
y[[0,2,4], :] # 和 y[np.array([0,2,4])] 效果一样，当时后者意义更明确

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

### 布尔或者掩模索引数组
### Boolean or "mask" index arrays
布尔数组被用作索引，以一种全新的角度看待索引数组。布尔数组必须和原始的维度一致。

In [69]:
b = y>20

In [70]:
y[b] # 布尔索引得到的是一个1维向量

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

不像整型索引数组，在布尔形式下，结果是1个一维数组包含了所有元素。

In [71]:
np.nonzero(b) # 得到的是一组点坐标

(array([3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6], dtype=int64))

In [72]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

如果布尔矩阵的维度小于y的维度，则结果会变成多维的。

In [73]:
b[:,5] # 使用1个1维布尔向量，当然确保其维度和y的第1维度相等，这样就是对行向量操作了

array([False, False, False,  True,  True], dtype=bool)

In [74]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

### 组合索引数组和切片的方法
### Combining index arrays with slices
索引数组可以和slices组合使用。比如：

In [75]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

事实上，切片被转换为了一个索引矩阵 np.array([[1,2]]) 它的形状为(1,2)，接着这个数组被广播为

In [76]:
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

In [77]:
b[:,5]

array([False, False, False,  True,  True], dtype=bool)

In [78]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

### 结构化索引工具

In [79]:
y.shape

(5, 7)

In [80]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [82]:
x = np.arange(5)

In [83]:
x

array([0, 1, 2, 3, 4])

In [84]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [85]:
x[:,None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [86]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [87]:
x[:,None]+x[None,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [88]:
z = np.arange(81).reshape(3,3,3,3)

In [89]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [90]:
z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [91]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [92]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [93]:
indices = (1,1,1,1)

In [94]:
z[indices]

40